### ISSUE TITLE
Proportion in citibikes_gender.ipynb

### ISSUE THREAD

**Issue by cmoscardi** [fedhere/PUI2017_fb55#1]
(I will make a PR to [the notebook](https://github.com/fedhere/PUI2017_fb55/blob/master/HW3_fb55/citibikes_gender.ipynb) tomorrow!)

Currently, the ratios tested are

M_{weekends} / M_{weekdays} 
and 
W_{weekends} / W_{weekdays}

This would be a ratio and does not necessarily end up as a proportion (e.g. if we compared W_{weekdays} / W_{weekends} , we'd have a ratio greater than 1).

I think these ratios should be normalized by total rides, so 
M_{weekends} / M_{total} vs. W_{weekends} / W_{total}

UPDATE: PR here! https://github.com/fedhere/PUI2017_fb55/pull/2

**Comment by fedhere** [comment]
accepted PR, thanks!
